name: cameraapp
description: A new Flutter application.

\version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  camera: ^0.5.8+2
  image_picker: ^0.6.7+4
  video_player: ^0.10.11+2
  path_provider: ^1.5.11
  gallery_saver: ^2.0.1
  path:
  geolocator: ^5.3.2+2
  flutter_spinkit: ^4.1.2
  #ftpconnect: ^0.1.6
  rflutter_alert: ^1.0.3
  ftpclient: ^0.8.0
  video_compress: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

